"""Release one subassembly from its shared PNG assets. No Blender needed here.
Run: python scripts/publish.py [--manifest path/to/assembly.json]
The default releases only CTRL001. Other assemblies are never rerendered.
"""
from pathlib import Path
import argparse, hashlib, html, json, shutil
from visual_standard import PDF_POINTS

ROOT = Path(__file__).resolve().parents[1]

def release(manifest_path):
    from reportlab.pdfgen import canvas
    from PIL import Image
    from pypdf import PdfReader
    m = json.loads(manifest_path.read_text(encoding='utf-8'))
    images = manifest_path.parent
    steps = m['steps']
    assert [s['number'] for s in steps] == list(range(1, len(steps)+1))
    for s in steps:
        with Image.open(images/s['image']) as im:
            assert im.size == (4400, 3000), f'Unexpected page dimensions: {s["image"]}'
            im.verify()
    pdf = ROOT/'pdf'/m['pdf']; pdf.parent.mkdir(exist_ok=True)
    c = canvas.Canvas(str(pdf), pagesize=PDF_POINTS, pageCompression=1, invariant=1)
    c.setTitle(m['title'].upper()+' — '+m['id']+' v'+str(m['revision']))
    c.setAuthor('Bearhawk Companion Visual Build Guide')
    c.setSubject('Illustrative quick-build assembly guide. Source flags require human review.')
    for s in steps:
        key=f'step-{s["number"]:02d}'
        c.bookmarkPage(key)
        c.addOutlineEntry(f'{s["number"]:02d} — {s["title"]}',key,level=0)
        c.drawImage(str(images/s['image']),0,0,width=PDF_POINTS[0],height=PDF_POINTS[1])
        c.showPage()
    c.save()
    reader=PdfReader(pdf)
    assert len(reader.pages)==len(steps)
    assert len(reader.outline)==len(steps)
    for page in reader.pages:
        assert tuple(float(v) for v in page.mediabox)==(0,0,*PDF_POINTS)
        assert len(page.images)==1
    # A generated byte-identical copy keeps /docs deployable by itself.
    web_pdf=ROOT/'docs'/'pdf'/pdf.name;web_pdf.parent.mkdir(exist_ok=True)
    shutil.copyfile(pdf,web_pdf)
    assert hashlib.sha256(pdf.read_bytes()).digest()==hashlib.sha256(web_pdf.read_bytes()).digest()
    route=ROOT/'docs'/m['slug'];route.mkdir(parents=True,exist_ok=True)
    asset_rel='../../../assets/images/'+images.name+'/'
    title=html.escape(m['title'])
    figures=[]
    for i,s in enumerate(steps):
        n=s['number'];image=asset_rel+s['image'];action=html.escape(s['title'].capitalize())
        prev=f'<a href="#step-{n-1}">← Previous</a>' if i else '<a href="../../../index.html">← Contents</a>'
        next_=f'<a href="#step-{n+1}">Next →</a>' if i<len(steps)-1 else '<a href="#top">Back to top ↑</a>'
        figures.append(f'''<figure class="step" id="step-{n}">
  <figcaption><span>{n:02d} / {len(steps):02d}</span><h2>{action}</h2><a href="{image}" target="_blank" rel="noopener" aria-label="Open step {n} at full size">Full size ↗</a></figcaption>
  <a class="page-image" href="{image}" target="_blank" rel="noopener" aria-label="Zoom step {n}: {action}"><img src="{image}" width="4400" height="3000" alt="Step {n}: {action}. Illustrated assembly, hardware and verification flags." loading="{'eager' if i==0 else 'lazy'}" decoding="async"></a>
  <nav class="step-nav" aria-label="Step {n} navigation">{prev}<span>{n} of {len(steps)}</span>{next_}</nav>
</figure>''')
    page=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} · Bearhawk Companion</title><meta name="description" content="Six visual steps for the Companion control-stick assembly and forward elevator controls, with a downloadable PDF.">
<link rel="stylesheet" href="../../../assets/css/manual.css">{favicon()}</head>
<body id="top"><a class="skip" href="#steps">Skip to steps</a>
<header class="bar"><a href="../../../index.html" class="brand">BEARHAWK <span>COMPANION</span></a><a class="pdf" href="../../../pdf/{html.escape(pdf.name)}" download>Download PDF ↓</a></header>
<main class="manual"><div class="assembly-heading"><p class="eyebrow">CONTROLS · CTRL–001 · v2</p><h1>{title}</h1><p class="hint">Tap a page for full-size viewing.</p><nav class="jump" aria-label="Jump to step">{''.join(f'<a href="#step-{n}">{n:02d}</a>' for n in range(1,len(steps)+1))}</nav></div>
<div id="steps">{''.join(figures)}</div>
<footer>ILLUSTRATIVE — NOT TO SCALE<br>Geometry: Bob Barrows Companion plans. QB hardware: current Companion count sheet.<br>Visible verification flags remain open.</footer></main></body></html>'''
    (route/'index.html').write_text(page,encoding='utf-8')
    # Rebuild only the small index from existing manifests. Preserve every other
    # assembly's page, image assets and PDF when releasing a single assembly.
    sections={}
    for existing in sorted((ROOT/'docs/assets/images').glob('*/assembly.json')):
        item=json.loads(existing.read_text(encoding='utf-8'))
        section=item['slug'].split('/')[0].replace('-',' ').title()
        item_title='Control Stick Assembly' if item['id']=='CTRL001' else item['title']
        card=f'''<a class="assembly-card" href="{html.escape(item['slug'])}/index.html"><img src="assets/images/{existing.parent.name}/{item['steps'][0]['image']}" width="4400" height="3000" alt="{html.escape(item_title)} installation illustration"><div><span class="eyebrow">{html.escape(item['id'])} · {len(item['steps'])} STEPS</span><h3>{html.escape(item_title)} <span aria-hidden="true">→</span></h3></div></a><a class="download-link" href="pdf/{html.escape(item['pdf'])}" download>Download {html.escape(item['pdf'])} ↓</a>'''
        sections.setdefault(section,[]).append(card)
    contents=''.join(f'<h2>{html.escape(section)}</h2>'+''.join(cards) for section,cards in sections.items())
    index=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bearhawk Companion Visual Build Guide</title><meta name="description" content="Illustrated quick-build assembly instructions for the Bearhawk Companion."><link rel="stylesheet" href="assets/css/manual.css">{favicon()}</head>
<body><header class="bar"><span class="brand">BEARHAWK <span>COMPANION</span></span></header>
<main class="contents"><p class="eyebrow">VISUAL BUILD GUIDE</p><h1>Bearhawk Companion<br>Visual Build Guide</h1>{contents}
<footer>ILLUSTRATIVE — NOT TO SCALE<br>Source documents control. Review the visible verification flags.</footer></main></body></html>'''
    (ROOT/'docs'/'index.html').write_text(index,encoding='utf-8')
    (ROOT/'docs'/'.nojekyll').touch()
    print(f'Released {m["id"]}: {len(steps)} pages; PDF and static pages validated.')

def favicon():
    return '<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 32 32%27%3E%3Crect width=%2732%27 height=%2732%27 rx=%276%27 fill=%27%23172C3C%27/%3E%3Cpath d=%27M8 24V14M24 24V14M8 18h16M10 14V7M22 14V7%27 fill=%27none%27 stroke=%27%2307B3EA%27 stroke-width=%273%27/%3E%3C/svg%3E">'

if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--manifest',type=Path,default=ROOT/'docs/assets/images/control-sticks/assembly.json')
    release(parser.parse_args().manifest.resolve())
